---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: detect-aws-credentials
      - id: check-merge-conflict
  - repo: https://github.com/bitmonkey/git-diff-check
    rev: 37d034abb7a5c0b4fd43b1a123efe8f2c00c5f8a
    hooks:
      - id: git-diff-check
  - repo: http://github.com/antonbabenko/pre-commit-terraform
    rev: v1.17.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate

