github_auth: &github_auth
  username: ((github.concourse_access_key))
  password: x-oauth-basic

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: registry-image-latest
  type: docker-image
  source:
    repository: concourse/registry-image-resource
    tag: latest

resources:
  - name: ui-image
    type: registry-image-latest
    source:
      repository: ips-ui
      tag: latest
      aws_access_key_id: ((ipsdev.access_key_id))
      aws_secret_access_key: ((ipsdev.secret_access_key))
      aws_region: eu-west-2
      aws_role_arn: ((ipsdev.deploy_role))
  
  - name: service-image
    type: registry-image-latest
    source:
      repository: ips-services
      tag: latest
      aws_access_key_id: ((ipsdev.access_key_id))
      aws_secret_access_key: ((ipsdev.secret_access_key))
      aws_region: eu-west-2
      aws_role_arn: ((ipsdev.deploy_role))

  - name: ips-repo
    type: git
    icon: &git-icon github-circle
    source:
      <<: *github_auth
      uri: https://github.com/ONSdigital/ips_aws_terraform.git
      branch: aws-b-migration-remove-peer

  - name: ips-service-git
    type: git
    icon: &git-icon github-circle
    source:
      <<: *github_auth
      uri: https://github.com/ONSdigital/ips_services.git
      branch: develop

  - name: ips-ui-git
    type: git
    icon: &git-icon github-circle
    source:
      <<: *github_auth
      uri: https://github.com/ONSdigital/ips_user_interface.git
      branch: develop

  - name: ips-sandbox-tf
    type: terraform
    source:
      env_name: sandbox
      backend_type: s3
      backend_config:
        bucket: socsur-ips-aws-b-services-terraform-state
        key: ips-concourse/terraform.tfstate
        dynamodb_table: socsur-ips-aws-b-services-terraform-locks
        region: eu-west-2
        access_key: ((ipsdev.access_key_id))
        secret_key: ((ipsdev.secret_access_key))
        role_arn: ((ipsdev.deploy_role))
      env:
        AWS_ACCESS_KEY_ID: ((ipsdev.access_key_id))
        AWS_SECRET_ACCESS_KEY: ((ipsdev.secret_access_key))

jobs:

  - name: build-ui
    serial: true
    plan:
      - in_parallel:
        - get: ips-ui-git
          trigger: true
        - get: ips-repo
          trigger: true
      - task: build-ui-image
        privileged: true
        file: ips-repo/tasks/build_image_ui/task.yml
      - put: ui-image
        params: {image: image/image.tar}

  - name: build-service
    serial: true
    plan:
      - in_parallel:
        - get: ips-service-git
          trigger: true
        - get: ips-repo
          trigger: true
      - task: build-service-image
        privileged: true
        file: ips-repo/tasks/build_image_service/task.yml
      - put: service-image
        params: {image: image/image.tar}

  - name: deploy-ips
    serial: true
    plan:
      - get: ips-repo
        trigger: true
        passed:
          - build-ui
          - build-service
      - put: ips-sandbox-tf
        params:
          terraform_source: ips-repo/terraform-infrastructure/
          vars:
            role_arn: ((ipsdev.deploy_role))
            environment_name: sandbox
            region: eu-west-2
            deploy_key_name: ConcDeploy
            common_name: ips-sandbox
            db_name: ips
            db_password: ((ips.ips_db_password))
            db_user_name: root
            ecr_repo: 970243148102.dkr.ecr.eu-west-2.amazonaws.com
            dns_zone_name: ons-ips-dev.uk.

  - name: ips-sql-schema
    serial: true
    plan:
      - in_parallel:
        - get: ips-repo
          passed: [deploy-ips]
          trigger: true
        - get: ips-service-git
        - get: ips-sandbox-tf
          passed: [deploy-ips]
      - task: insert-ips-sql-schema
        file: ips-repo/tasks/sql_schema/task.yml
        input_mapping:
          terraform: ips-sandbox-tf
        params:
          AWS_ACCESS_KEY_ID: ((ipsdev.access_key_id))
          AWS_SECRET_ACCESS_KEY: ((ipsdev.secret_access_key))
          AWS_ROLE_ARN: ((ipsdev.deploy_role))
