github_auth: &github_auth
  username: ((github.concourse_access_key))
  password: x-oauth-basic

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
  - name: ips-repo
    type: git
    icon: &git-icon github-circle
    source:
      <<: *github_auth
      uri: https://github.com/ONSdigital/ips_aws_terraform.git
      branch: aws-b-migration-remove-peer

  - name: ips-sandbox-tf
    type: terraform
    source:
      env_name: sandbox
      backend_type: s3
      backend_config:
        bucket: socsur-ips-aws-b-services-terraform-state
        key: ips-concourse/terraform.tfstate
        dynamodb_table: socsur-ips-aws-b-services-terraform-locks
        region: eu-west-2
        access_key: ((ipssandbox.concourse_user_id))
        secret_key: ((ipssandbox.concourse_user_secret))
        role_arn: ((ipssandbox.deploy_role))
      env:
        AWS_ACCESS_KEY_ID: ((ipssandbox.concourse_user_id))
        AWS_SECRET_ACCESS_KEY: ((ipssandbox.concourse_user_secret))

jobs:

  - name: destroy-ips-sandbox
    plan:
      - get: ips-repo
      - put: ips-sandbox-tf
        get_params:
          action: destroy
        params:
          terraform_source: ips-repo/terraform-infrastructure/
          action: destroy
          vars:
            role_arn: ((ipssandbox.deploy_role))
            environment_name: sandbox
            region: eu-west-2
            bastion_ingress_ip: 94.6.14.81
            deploy_key_name: ConcDeploy
            common_name: ips-sandbox
            db_name: ips
            db_password: ((ips.ips_db_password))
            db_user_name: root
            arn_certificate: ((ipssandbox.arn_certificate))
