platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
params:
  SECRET_VALUE: ((ipssandbox.secret_access_key))
run:
  path: /bin/sh
  args:
    - -ce
    - echo "${SECRET_VALUE}"
