platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/cloud-builders/kubectl
params:
  SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
  CONCOURSE_TEAM: social-surveys
  SECRET_KEY:
  SECRET_NAME:
inputs:
  - name: encrypted_secret
run:
  path: /bin/bash
  args:
    - -ce
    - |-
      cat >~/gcloud-service-key.json <<EOL
      $SERVICE_ACCOUNT_JSON
      EOL
      gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      gcloud container clusters get-credentials k8s-ci --zone europe-west2 --project ons-ci --internal-ip
      cat encrypted_secret/secret | base64 -d | gcloud kms decrypt --project ons-ci --location europe-west2 --keyring concourse --key "${CONCOURSE_TEAM}" --plaintext-file "${SECRET_KEY}" --ciphertext-file -
      kubectl create secret generic "${SECRET_NAME}" -n "concourse-${CONCOURSE_TEAM}" --from-env-file="${SECRET_KEY}" --dry-run -o yaml | kubectl apply -f -