
jobs:
- name: set-secret
  plan:
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: gcr.io/cloud-builders/kubectl
        type: registry-image
      params:
        SECRET_NAME: cognito-uat-role
        SECRET_VALUE: 
        SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
        TEAM_NAME: spp-crosscutting
      platform: linux
      run:
        args:
        - -ce
        - |-
          cat >~/gcloud-service-key.json <<EOL
          $SERVICE_ACCOUNT_JSON
          EOL
          gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
          gcloud container clusters get-credentials k8s-ci --zone europe-west2 --project ons-ci --internal-ip
          echo -n "${SECRET_VALUE}" | base64 -d | gcloud kms decrypt --project ons-ci --location europe-west2 --keyring concourse --key $TEAM_NAME --plaintext-file secret_source --ciphertext-file -
          kubectl create secret generic $SECRET_NAME -n "concourse-${TEAM_NAME}" --from-env-file=secret_source --dry-run -o yaml | kubectl apply -f -
        path: /bin/bash
    task: set-secrets