
jobs:
- name: set-secret
  plan:
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: gcr.io/cloud-builders/kubectl
        type: registry-image
      params:
        SECRET_NAME: ipssandbox
        SECRET_VALUE: CiQA/MLnXUW+0T0kSwoSHUT8Ce+cPgCt3ikfyGR67mbU/Uz3co4SsQIAc69jmqzokQ0sJk9R+vcH4zxvAOTg+/xcznQjfGYj7d/Tgp/03Q5mkTjHlFNcpMb6ttN6XBkuoCupgjdAXmvM+gV8pB9c7kXtzYJD3G9RrVRRL1u8Q5Dfh7wH0CUglHK5zSgwcb10LVttR0SAF2Ll4MQwyy1c/iDkBV0pYqIFM9z8Xgyi0NrvuIWOxGELiYzMkZhTyV8V3RqrNbBuY1ly2TGIRuc/sarF1fnxewVwQHOTCx5JT4RWcqoSxM1QJ9/fUnjkGQWCQO6vJEd7e2MOP13DXXlBwqG1kqB7PcqOB81nHJy4h9iQMLzDXA6noFU5/zY5NzEV6tqIghQiG/zwhVKqL7s29gbIFlbaq5kijSjz+udEfwRx20B+emuTSBDfKVIBXImOSCK1HrbPLd3dyg==
        SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
        TEAM_NAME: social-surveys
      platform: linux
      run:
        args:
        - -ce
        - |-
          cat >~/gcloud-service-key.json <<EOL
          $SERVICE_ACCOUNT_JSON
          EOL
          gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
          gcloud container clusters get-credentials k8s-ci --zone europe-west2 --project ons-ci --internal-ip
          echo -n "${SECRET_VALUE}" | base64 -d | gcloud kms decrypt --project ons-ci --location europe-west2 --keyring concourse --key $TEAM_NAME --plaintext-file secret_source --ciphertext-file -
          kubectl create secret generic $SECRET_NAME -n "concourse-${TEAM_NAME}" --from-env-file=secret_source --dry-run -o yaml | kubectl apply -f -
        path: /bin/bash
    task: set-secrets