---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: latest
inputs:
  - name: ips-repo
run:
  path: ./ips-repo/tasks/terraform-format/task.sh